name: StaffPlus
version: 3.0.6
description: The ultimate moderation plugin!
author: Shortninja
website: http://shortninja.net
main: net.shortninja.staffplus.StaffPlus
softdepend: [PacketListenerApi]